def gen_slots():
    area_slots = [
        "Duomo",
        "Brera",
        "Giardini Porta Venezia",
        "Guastalla",
        "Porta Vigentina - Porta Lodovica",
        "Porta Ticinese - Conca del Naviglio",
        "Magenta - San Vittore",
        "Parco Sempione",
        "Porta Garibaldi - Porta Nuova",
        "Stazione Centrale - Ponte Seveso",
        "Isola",
        "Maciachini - Maggiolina",
        "Greco - Segnano",
        "Niguarda - Ca’ Granda - Prato Centenaro - Q.re Fulvio Testi",
        "Bicocca",
        "Gorla - Precotto",
        "Adriano",
        "Cimiano - Rottole - Q.re Feltre",
        "Padova - Turro - Crescenzago",
        "Loreto - Casoretto - NoLo",
        "Buenos Aires - Porta Venezia - Porta Monforte",
        "CIttà studi",
        "Lambrate - Ortica",
        "Parco Forlanini - Cavriano",
        "Corsica",
        "XXII Marzo",
        "Porta Romana",
        "Umbria - Molise - Calvairate",
        "Ortomercato",
        "Taliedo - Morsenchio - Q.re Forlanini",
        "Monluè - Ponte Lambro",
        "Triulzo Superiore",
        "Rogoredo - Santa Giulia",
        "Chiaravalle",
        "Lodi-Corvetto",
        "Scalo Romana",
        "Morivione",
        "Vigentino - Q.re Fatima",
        "Quintosole",
        "Ronchetto delle Rane",
        "Gratosoglio - Q.re Missaglia - Q.re Terrazze",
        "Stadera - Chiesa Rossa - Q.re Torretta - Conca Fallata",
        "Tibaldi",
        "Porta Ticinese - Conchetta",
        "Moncucco - San Cristoforo",
        "Barona",
        "Cantalupa",
        "Ronchetto sul Naviglio - Q.re Lodovico il Moro",
        "Giambellino",
        "Porta Genova",
        "Porta Magenta",
        "Bande Nere",
        "Lorenteggio",
        "Muggiano",
        "Baggio - Q.re degli Olmi - Q.re Valsesia",
        "Forze Armate",
        "San Siro",
        "De Angeli - Monte Rosa",
        "Tre Torri",
        "Stadio - Ippodromi",
        "Quarto Cagnino",
        "Quinto Romano",
        "Figino",
        "Trenno",
        "Q.re Gallaratese - Q.re San Leonardo - Lampugnano",
        "QT8",
        "Portello",
        "Pagano",
        "Sarpi",
        "Ghisolfa",
        "Villapizzone - Cagnola - Boldinasco",
        "Maggiore - Musocco - Certosa",
        "MIND - Cascina Triulza",
        "Roserio",
        "Stephenson",
        "Quarto Oggiaro - Vialba - Musocco",
        "Bovisa",
        "Farini",
        "Dergano",
        "Affori",
        "Bovisasca",
        "Comasina",
        "Bruzzano",
        "Parco Nord",
        "Parco delle Abbazie",
        "Parco dei Navigli",
        "Assiano",
        "Parco Bosco in città"
    ]

    time_slots = [
        "Sabato 14 marzo ore 11:00 - 12:30",
        "Sabato 14 marzo ore 15:00 - 16:30",
        "Domenica 15 marzo ore 11:00 - 12:30",
        "Domenica 15 marzo ore 15:00 - 16:30"
    ]

    return area_slots, time_slots
